version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hotelease_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - hotelease_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hotelease_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hotelease_network

networks:
  hotelease_network:
    driver: bridge
