apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-dynamic
  namespace: hotelease
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi