apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: hotelease
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv


  # claim used by pod to get its data stored in the volume whose structure defined in mongo-pv.yml file