apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hotelease
type: Opaque
data:
  MONGO_URI: <base64-encode-your-own-mongo-uri>
  JWT_SECRET: <base64-encode-your-own-jwt-secret>
  CLOUDINARY_API_SECRET: <base64-encode-your-own-cloudinary-secret>
  